language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - cd task11.1
  - docker-compose up -d
  - cd ..

install:
  - pip install -r requirements.txt

script:
  - cd task11.1
  - pytest
