language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - docker-compose up -f task11.1/docker-compose.yml -d

install:
  - pip install -r requirements.txt

script:
  - cd task11.1
  - pytest
