language: python

python:
  - "3.6"

services:
  - docker

env:
  global:
    - IMAGE_NAME=task111_echo-server

install:
  - pip install -r requirements.txt

before_script:
  - cd task11.1
  - docker-compose up -d

script:
  - pytest

after_success:
  # DOCKER_USERNAME and DOCKER_PASSWORD stored in Travis CI Web interface
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker images
  - docker tag ${IMAGE_NAME} $DOCKER_USERNAME/http-server
  - docker push $DOCKER_USERNAME/http-server
