language: python

python:
  - "3.6"

services:
  - docker

env:
  global:
    - IMAGE_NAME=task111_echo-server

install:
  - pip install -r requirements.txt

before_script:
  - cd task11.1
  - docker-compose up -d

script:
  - pytest

after_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker tag "${IMAGE_NAME}" "$DOCKER_USERNAME"/http-server:latest
  - docker push "$DOCKER_USERNAME"/http-server:latest
