language: python

python:
  - "3.6"

services:
  - docker

env:
  global:
    - IMAGE_NAME=task111_echo-server

install:
  - pip install -r requirements.txt

before_script:
  - cd task11.1
  - docker-compose up -d

script:
  - pytest

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest"

